FinalProject/Areas/Admin/ViewModels/BannerViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.ComponentModel.DataAnnotations;
using static Common.ValidationConstant;
using static Common.DisplayNameConstant;

namespace FinalProject.Areas.Admin.ViewModels
{
    public class BannerViewModel
    {
        public int BannerId { get; set; }

        [Required(ErrorMessage = ERROR_BANNER_IMAGE_EMPTY)]
        [Display(Name = DISPLAY_BANNER_IMAGE)]
        public IFormFile Image { get; set; }

        public string ImageString { get; set; }

        [Required(ErrorMessage = ERROR_BANNER_START_DATE_EMPTY)]
        [Display(Name = DISPLAY_BANNER_START_DATE)]
        public DateTime StartDate { get; set; } = DateTime.Now;

        [Required(ErrorMessage = ERROR_BANNER_END_DATE_EMPTY)]
        [Display(Name = DISPLAY_BANNER_END_DATE)]
        public DateTime EndDate { get; set; }

        [Display(Name = DISPLAY_BANNER_URL)]
        public string Url { get; set; } = "Default";
    }
}

FinalProject/Areas/Admin/Controllers/BannerController.cs
using Entities.Models;
using FinalProject.Areas.Admin.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Interfacies;
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;
using static Common.Constant;
using static Common.MessageConstant;
using static Common.RoleConstant;
using static Common.ValidationConstant;
using static FinalProject.Areas.Admin.Helpers.BannerHelper;
using static FinalProject.Areas.Admin.Helpers.ImageHelper;

namespace FinalProject.Areas.Admin.Controllers
{
    [Area(AREA_ADMIN)]
    [Authorize(Roles = ROLE_ADMIN, AuthenticationSchemes = ROLE_ADMIN)]
    public class BannerController : Controller
    {
        private readonly IBannerService _bannerService;

        public BannerController(IBannerService bannerService)
        {
            _bannerService = bannerService;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Banners = await _bannerService.GetAllBannerAsync();

            return View();
        }

        public IActionResult AddBanner()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddBanner(BannerViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var imageName = await SaveImageBannerAsync(model.Image, 1366, 768);

                    if (!(imageName is null))
                    {
                        using var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);

                        var banner = new Banner()
                        {
                            StartDate = model.StartDate,
                            EndDate = model.EndDate,
                            Image = imageName,
                            Url = model.Url
                        };

                        var result = await _bannerService.AddBannerAsync(banner);

                        if (result > 0)
                        {
                            transaction.Complete();

                            TempData["MessageSuccess"] = MESSAGE_SUCCESS_ADD_BANNER;

                            return Redirect("/Admin/Banner/Index");
                        }
                    }
                }
                catch
                {
                }
            }

            ViewBag.MessageError = MESSAGE_ERROR_SYSTEM;

            return View(model);
        }

        [HttpDelete]
        public async Task<int> DeleteBanner(int? bannerId)
        {
            if (bannerId is null)
            {
                return ERROR_CODE_NULL;
            }

            using var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);
            try
            {
                var result = await _bannerService.DeleteBannerAsync(bannerId.Value);

                if (result > 0)
                {
                    transaction.Complete();

                    return CODE_SUCCESS;
                }
            }
            catch { }

            return ERROR_CODE_SYSTEM;
        }

        public async Task<IActionResult> EditBanner(int? bannerId)
        {
            if (bannerId is null)
            {
                return PartialView(ERROR_404_PAGE_ADMIN);
            }

            var banner = await _bannerService.GetBannerByIdAsync(bannerId.Value);

            if (banner != null)
            {
                var model = ConvertBannerToBannerViewModel(banner);

                return View(model);
            }

            return PartialView(ERROR_404_PAGE_ADMIN);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditBanner(BannerViewModel model, string imagePreviewDeteted)
        {
            ModelState.Remove(KEY_IMAGE);

            var banner = await _bannerService.GetBannerByIdAsync(model.BannerId);

            if (ModelState.IsValid)
            {
                try
                {
                    string imageName = EMPTY;

                    if (imagePreviewDeteted != null)
                    {
                        var image = imagePreviewDeteted.Split(COMMA);

                        if (image.Contains(model.Image.FileName))
                        {
                            model.Image = null;
                        }
                    }

                    if (model.Image == null && model.ImageString == null)
                    {
                        ViewBag.MessageError = ERROR_BANNER_IMAGE_EMPTY;

                        model.ImageString = banner.Image;

                        return View(model);
                    }
                    else if (model.Image != null)
                    {

                        imageName = await SaveImageBannerAsync(model.Image, 1920, 768);
                    }
                    else if (model.ImageString != null)
                    {
                        imageName = model.ImageString;
                    }

                    banner.BannerId = model.BannerId;
                    banner.StartDate = model.StartDate;
                    banner.EndDate = model.EndDate;
                    banner.Image = imageName;
                    banner.Url = model.Url;

                    using var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);

                    var result = await _bannerService.UpdateBannerAsync(banner);

                    if (result > 0)
                    {
                        transaction.Complete();

                        TempData["MessageSuccess"] = MESSAGE_BANNER_UPDATE_SUCCESS;

                        model.ImageString = imageName;

                        return Redirect("/Admin/Banner/Index");
                    }
                }

                catch { }

            }

            model.ImageString = banner.Image;

            ViewBag.MessageError = MESSAGE_BANNER_UPDATE_FAIL;

            return View(model);
        }
    }
}

FinalProject/Controllers/CartController.cs
using static Common.Constant;
using static Common.RoleConstant;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Services.Interfacies;
using System;
using System.Threading.Tasks;
using System.Transactions;
using Microsoft.AspNetCore.Authorization;

namespace FinalProject.Controllers
{
    [Authorize(Roles = ROLE_CUSTOMER, AuthenticationSchemes = ROLE_CUSTOMER)]
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly IAccountService _accountService;

        public CartController(ICartService cartService, IAccountService accountService)
        {
            _cartService = cartService;
            _accountService = accountService;
        }

        [HttpPost]
        public async Task<string> AddToCart(int? productDetailId, int? quantity, decimal? price)
        {
            if (productDetailId is null || quantity is null || price is null)
                return MISS_VALUE;

            using (var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                var userId = _accountService.GetUserId(User);

                var cartItem = await _cartService.GetCartItemsAsync(productDetailId.Value, userId);

                if (cartItem is null)
                {
                    var cart = new CartItem()
                    {
                        UserId = userId,
                        ProductDetailId = productDetailId.Value,
                        Quantity = quantity.Value,
                        CreateDate = DateTime.Now,
                        Price = price.Value
                    };

                    var result = await _cartService.AddToCartAsync(cart);

                    if (!(result is null))
                    {
                        transaction.Complete();

                        return JsonConvert.SerializeObject(result);
                    }
                }
                else
                {
                    cartItem.Quantity = quantity.Value;

                    var result = await _cartService.UpdateCartItemAsync(cartItem);

                    if (!(result is null))
                    {
                        transaction.Complete();

                        return UPDATED;
                    }
                }
            }

            return EMPTY;
        }

        [HttpDelete]
        public async Task<string> RemoveCartItem(int? productDetailId)
        {
            var userId = _accountService.GetUserId(User);

            if (productDetailId is null || userId is null)
            {
                return MISS_VALUE;
            }

            using (var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                var result = await _cartService.DeleteCartItemAsync(productDetailId.Value, userId);

                if (result > 0)
                {
                    transaction.Complete();

                    return SUCCESS;
                }
            }

            return FAIL;
        }

        [HttpGet]
        public decimal GetCartTotal()
        {
            var userId = _accountService.GetUserId(User);

            decimal total = _cartService.GetCartTotalByUserId(userId);

            return total;
        }

        public async Task<IActionResult> Checkout()
        {
            var userId = _accountService.GetUserId(User);

            ViewBag.CartItems = await _cartService.GetCartsByUserIdAsync(userId);

            ViewBag.CartTotal = _cartService.GetCartTotalByUserId(userId);

            return View();
        }

        [HttpPut]
        public async Task<decimal> ChangeQuantityCartItem(int? productDetailId, int? quantity)
        {

            if (productDetailId is null || quantity is null)
                return ERROR_CODE_NULL;

            using (var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                var userId = _accountService.GetUserId(User);

                var result = await _cartService
                    .UpdateQuantityOfCartItemAsync(productDetailId.Value, quantity.Value, userId);
                
                if(result > 0)
                {
                    var total = _cartService.GetCartTotalByUserId(userId);

                    transaction.Complete();

                    return total;

                }

            }

            return ERROR_CODE_SYSTEM;
        }
    }
}

FinalProject/Controllers/GuideController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Services.Interfacies;
using System;
using System.Threading.Tasks;

namespace FinalProject.Controllers
{
    public class GuideController : Controller
    {
        private readonly IFileGuideService _fileGuideService;
        private readonly IMemoryCache _memoryCache;

        public GuideController(IFileGuideService fileGuideService, IMemoryCache memoryCache)
        {
            _fileGuideService = fileGuideService;
            _memoryCache = memoryCache;
        }
        public IActionResult GuideBuyProduct()
        {
            return View();
        }
        public IActionResult GuidePayment()
        {
            return View();
        }

        public async Task<IActionResult> Download(string type)
        {
            bool cached = _memoryCache.TryGetValue(type, out FileGuide fileGuide);
            byte[] bytes;
            string contentType;
            if (!cached)
            {
                var result = await _fileGuideService.DownloadFileAsync(type);

                _memoryCache.Set(type, result);

                bytes = Convert.FromBase64String(result.Content);

                contentType = result.ContentType;
            }
            else
            {
                bytes = Convert.FromBase64String(fileGuide.Content);

                contentType = fileGuide.ContentType;
            }

            var file = new FileContentResult(bytes, contentType);

            return file;
        }
    }
}

FinalProject/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Interfacies;
using System.Collections.Generic;
using System.Threading.Tasks;
using X.PagedList;
using static Common.Constant;

namespace FinalProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICommentService _commentService;
        private readonly IRatingService _rateService;
        private readonly IUserConnectionService _userConnectionService;
        private readonly IRecommendationService _recommendationService;

        public ProductController(IProductService productService, ICommentService commentService, IRecommendationService recommendationService, IRatingService rateService, IUserConnectionService userConnectionService)
        {
            _productService = productService;
            _commentService = commentService;
            _recommendationService = recommendationService;
            _rateService = rateService;
            _userConnectionService = userConnectionService;
        }
        public async Task<IActionResult> Detail(int? id, int? page = 1)
        {
            if(id is null)
            {
                return PartialView(ERROR_404_PAGE);
            }

            var userConnection = Request.HttpContext.Connection.RemoteIpAddress;

            await _userConnectionService.AddUserConnectionAsync(userConnection.ToString(), id.Value);

            ViewBag.Product = await _productService.GetProductByIdAsync(id.Value);

            ViewBag.Comments = await _commentService.GetAllCommentsByProductIdAsync(id.Value);

            ViewBag.Ratings = await _rateService.GetRatingsAsync();

            ViewBag.RatingsDetail = await _rateService.GetRatingsDetailAsync(id.Value);

            var listProductDetailId = await _productService.GetProductDetailByProDuctIdAsync(id.Value);

            var productSuggests = await _recommendationService.GetSuggestedProduct(listProductDetailId);

            var model = productSuggests.ToPagedList(page.Value, 12);

            return View(model);
        }

        public string GetProductSkip(int? skip)
        {
            if(skip is null)
            {
                return ERROR_CODE_NULL.ToString();
            }

            try
            {
                return _productService.GetProductSkip(skip.Value);
            }
            catch
            {

            }

            return ERROR_CODE_SYSTEM.ToString();
        }
    }
}

FinalProject/Views/Shared/_Banner.cshtml
@inject Services.Interfacies.IBannerService _bannerService
@{ 
    var banners = await _bannerService.GetBannerAsync();
    var rnd = new Random();
}
<div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
    <div class="box-slide-show">
        <div class="slide-show">
            <div class="vt-slideshow">
                <ul>
                    @if (!(banners is null) && !(banners.FirstOrDefault() is null))
                    {
                        foreach (var item in banners)
                        {
                            int num = rnd.Next(1, 5);

                            string className = "slide" + num.ToString();

                            <li class="@className" data-transition="random"><img src="~/images/banner/@item.Image" alt="Banner" /></li>
                        }
                    }
                    else
                    {
                        int num = rnd.Next(1, 5);

                        string className = "slide" + num.ToString();

                        <li class="@className" data-transition="random"><img src="~/images/banner/banner-default.jpg" alt="Banner" /></li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>

FinalProject/Views/Shared/_Footer.cshtml
@inject Services.Interfacies.IAccountService _accountService
@{ 
    string userId = Guid.Empty.ToString();
    if(User != null && User.Identity.IsAuthenticated)
    {
        userId = _accountService.GetUserId(User);
    }
}
<div id="box-footer">
    <div class="box-footer-top">
        <div class="container">
            <div class="row">
                <div class="row">
                    <div class="box-connect col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        <div class="block-title"><span>Kết nối với chúng tôi</span></div>
                        <a href="#" class="face-book">face book</a>
                        <a href="#" class="tweeter">tweeter</a>
                        <a href="#" class="pinseter">pinseter</a>
                        <a href="#" class="google">google+</a>
                    </div>
                    <div class="box-newletter col-lg-6 col-md-6 col-sm-6 col-xs-6">
                        <div class="block-title"><span>Đăng ký nhận tin</span></div>
                        <div class="content">
                            <form action="#" method="post">
                                <input name="newletter" type="text" class="newletter" placeholder="Nhập địa chỉ email của bạn" />
                                <button><span>Đăng ký</span></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer-middle">
        <div class="container">
            <div class="row">
                <div class="row">
                    <div class="block block-info col-lg-3 col-md-3 col-sm-3 col-xs-12">
                        <div class="block-title"><span>Thông tin chung</span></div>
                        <div class="block-content">
                            <ul>
                                <li><a href="#">Giới thiệu</a></li>
                                <li><a href="#">Vị trí cửa hàng</a></li>
                                <li><a href="#">Tìm kiếm nâng cao</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="block block-customer col-lg-3 col-md-3 col-sm-3 col-xs-12">
                        <div class="block-title"><span>Dịch vụ khách hàng</span></div>
                        <div class="block-content">
                            <ul>
                                <li><a asp-action="CheckOut" asp-controller="Cart">Xem giỏ hàng</a></li>
                                <li><a asp-action="Information" asp-controller="Account">Xem thông tin tài khoản</a></li>
                                <li><a asp-action="Orders" asp-controller="Order" asp-route-userId="@userId">Thông tin đơn hàng</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="block block-galary col-lg-3 col-md-3 col-sm-3 col-xs-12">
                        <div class="block-title"><span>Hướng dẫn mua hàng</span></div>

                        <div class="block-content">
                            <ul>
                                <li><a asp-action="GuideBuyProduct" asp-controller="Guide">Cách thức mua hàng</a></li>
                                @*<li><a href="#">Câu hỏi thường gặp</a></li>*@
                                <li><a asp-action="GuidePayment" asp-controller="Guide">Phương thức thanh toán</a></li>
                                <li><a href="#">Phương thức vận chuyển</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="block block-cu col-lg-3 col-md-3 col-sm-3 col-xs-12">
                        <div class="block-title"><span>Liên hệ với chúng tôi</span></div>
                        <div class="block-content">
                            <ul>
                                <li class="item1"><span>Cửa hàng đồ dùng học tập <br />Stationery Store</span></li>
                                <li class="item2"><span>+ 84 359554019</span></li>
                                <li class="item3"><a href="mailto:StationeryStore.HCM01@gmail.com">StationeryStore.HCM01@gmail.com</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer-bottom">
        <div class="container">
            <div class="row">
                <div class="box-left">
                    <ul>
                        <li class="home"><a>Stationery Store</a></li>
                        <li><a href="#">Về chúng tôi   </a><span>|</span></li>
                        <li><a href="#">Giao hàng & Trả hàng</a><span>|</span></li>
                        <li><a href="#">Liên hệ với chúng tôi</a></li>
                    </ul>
                    <h6>Stationery Store &copy; 2021</h6>
                </div>
                <div class="box-right">
                    <ul>
                        <li><img src="~/images/logo/cod.png" alt="Thanh toán bằng COD" width="60" height="30"/></li>
                        <li><img src="~/images/logo/momo.png" alt="Thanh toán bằng ví MoMo"  width="60" height="30"/></li>
                        <li><img src="~/images/logo/paypal.png" alt="Thanh toán bằng ví Paypal"  width="60" height="30"/></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <a id="gototop">Top</a>
</div>

FinalProject/Views/Shared/_Navigation.cshtml
@inject Services.Interfacies.ICategoryService _categoryService
@inject Services.Interfacies.IProductService _productService
@{ 
    var categories = await _categoryService.GetAllCategoriesAsync();
    var productDetails = await _productService.GetTop10ProductHotAsync();
}

<div class="box-header-02">
    <div class="container">
        <div class="row">
            <div class="menu">
                <div class="box-main-menu">
                    <div class="main-menu">
                        <ul>
                            <li class="item1 first"><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
                            <li class="item2 megamenu-parent">
                                <a href="#">Danh mục sản phẩm</a>
                                <div class="vt_megamenu_content">
                                    <div class="mega-menu-01">
                                        <div class="menu-01 menu-01-cate">
                                            <div class="title"><span>Loại sản phẩm</span></div>
                                            <ul class="content-col" style="overflow-y: scroll; height: 240px;">
                                                @if (categories != null && categories.Any())
                                                {
                                                    foreach (var item in categories)
                                                    {
                                                        <li style="padding: 5px"><a asp-action="Search" asp-controller="Search" asp-route-text="@item.CategoryName"><span>@item.CategoryName</span></a></li>
                                                    }
                                                }
                                            </ul>
                                        </div>
                                        <div class="menu-01 menu-01-top">
                                            <div class="title"><span>Sản phẩm</span><span class="hot">Hot</span></div>
                                            <ul class="content-col">
                                                @if (productDetails != null && productDetails.Any())
                                                {
                                                    foreach(var item in productDetails.Take(5))
                                                    {
                                                        <li>
                                                            <a asp-action="Detail" asp-controller="Product" asp-route-id="@item.ProductId">
                                                                <span>@item.Product.ProductName phân loại @item.Color</span>
                                                            </a>
                                                        </li>
                                                    }
                                                }
                                            </ul>
                                        </div>
                                        @if(productDetails != null && productDetails.Count > 5)
                                        {
                                            <div class="menu-01 menu-01-top">
                                                <div class="title"><span>Sản phẩm</span><span class="hot">Hot</span></div>
                                                <ul class="content-col">
                                                    @foreach(var item in productDetails.Skip(5))
                                                    {
                                                        <li>
                                                            <a asp-action="Detail" asp-controller="Product" asp-route-id="@item.ProductId">
                                                                <span>@item.Product.ProductName phân loại @item.Color</span>
                                                            </a>
                                                        </li>
                                                    }
                                                </ul>
                                            </div>
                                        }
                                        @*<div id="feature" class="menu-01 menu-01-feature carousel-feature">
                                            <div class="title"><span>Featured</span><span class="new">New</span></div>
                                            <div class="carousel-inner">
                                                <div class="item active">
                                                    <div class="image"><img alt="" src="images/feature-mega01.png" /></div>
                                                    <div class="carousel-caption-feature">
                                                        <div class="title-advan">
                                                            <span class="name-advan">Ipad Air and iOS7</span>
                                                            <div class="text-des-advan"><span>At vero eos et accusamus et iusto odios un dignissimos ducimus qui blan ditiis prasixer esentium voluptatum</span></div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="item">
                                                    <div class="image"><img alt="" src="images/feature-mega01.png" /></div>
                                                    <div class="carousel-caption-feature">
                                                        <div class="title-advan">
                                                            <span class="name-advan">Ipad Air and iOS7</span>
                                                            <div class="text-des-advan"><span>At vero eos et accusamus et iusto odios un dignissimos ducimus qui blan ditiis prasixer esentium voluptatum</span></div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="item">
                                                    <div class="image"><img alt="" src="images/feature-mega01.png" /></div>
                                                    <div class="carousel-caption-feature">
                                                        <div class="title-advan">
                                                            <span class="name-advan">Ipad Air and iOS7</span>
                                                            <div class="text-des-advan"><span>At vero eos et accusamus et iusto odios un dignissimos ducimus qui blan ditiis prasixer esentium voluptatum</span></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="menu-01 menu-01-sale">
                                            <div class="title"><span>Sale</span></div>
                                            <div class="content">
                                                <img alt="" src="images/sale-mega-01.png" />
                                                <p class="description">At vero eos et accusamus et iusto odios un dignissimos ducimus qui blan ditiis prasixer esentium voluptatum</p>
                                                <div class="shop-now"><a title="Shop now" href="#"><span>Shop now</span></a></div>
                                            </div>
                                        </div>*@
                                    </div>
                                </div>
                            </li>
                            <li class="item3"><a asp-action="SaleProduct" asp-controller="Home">Sản phẩm khuyến mại </a></li>
                            <li class="item4"><a href="javascript:void(0)">Giới thiệu </a></li>
                            <li class="item5"><a href="javascript:void(0)">Liên hệ </a></li>
                        </ul>
                    </div>
                </div>
            </div>
        <div class="bgr-menu">
        </div>
        </div>
    </div>
</div>