FinalProject/Areas/Admin/Controllers/SaleController.cs
using static Common.Constant;
using static Common.RoleConstant;
using static Common.SignalRConstant;
using static FinalProject.Areas.Admin.Helpers.ImageHelper;
using static FinalProject.Areas.Admin.Helpers.SaleHelper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Interfacies;
using System.Threading.Tasks;
using FinalProject.Areas.Admin.ViewModels;
using System.Transactions;
using Entities.Models;
using System.Linq;
using System;
using Microsoft.AspNetCore.SignalR;
using Services.Hubs;
using System.Collections.Generic;

namespace FinalProject.Areas.Admin.Controllers
{
    [Area(AREA_ADMIN)]
    [Authorize(Roles = ROLE_ADMIN, AuthenticationSchemes = ROLE_ADMIN)]
    public class SaleController : Controller
    {
        private readonly IProductService _productService;
        private readonly ISaleDetailService _saleDetailService;
        private readonly ISaleService _saleService;
        private readonly IHubContext<SignalServer> _hubContext;
        private readonly INotificationService _notificationService;
        private readonly IAccountService _accountService;
        private readonly IProductDetailService _productDetailService;

        public SaleController(IProductService productService, ISaleService saleService, ISaleDetailService saleDetailService, INotificationService notificationService, IHubContext<SignalServer> hubContext, IAccountService accountService, IProductDetailService productDetailService)
        {
            _productService = productService;
            _saleDetailService = saleDetailService;
            _saleService = saleService;
            _hubContext = hubContext;
            _notificationService = notificationService;
            _accountService = accountService;
            _productDetailService = productDetailService;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.Sales = await _saleService.GetSalesAsync();

            return View();
        }

        [HttpDelete]
        public async Task<int> DeleteSale(int? saleId)
        {
            if(saleId is null)
            {
                return ERROR_CODE_NULL;
            }

            using var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);
            try
            {
                var result = await _saleService.DeleteSaleByIdAsync(saleId.Value);

                if(result > 0)
                {
                    transaction.Complete();

                    return CODE_SUCCESS;
                }
            }
            catch
            {

            }

            return ERROR_CODE_SYSTEM;
        }

        public async Task<IActionResult> EditSale(int? saleId)
        {
            if(saleId is null)
            {
                return PartialView(ERROR_404_PAGE_ADMIN);
            }

            ViewBag.Products = await _productService.GetProductsCanApplySaleAsync();

            var sale = await _saleService.GetSaleByIdAsync(saleId.Value);

            var model = new SaleViewModel()
            {
                SaleId = sale.SaleId,
                SaleName = sale.SaleName,
                SaleStartDate = sale.SaleStartDate,
                SaleEndDate = sale.SaleEndDate,
                SaleType = sale.SaleType,
                Description = sale.Description,
                Discount = sale.Discount,
                FromOrderPrice = sale.FromOrderPrice,
                Image = sale.Image
            };

            if(sale.SaleDetails != null && sale.SaleDetails.Any())
            {
                model.ProductIds = sale.SaleDetails.Select(x => x.ProductId).ToList();

                ViewBag.ProductInSales = await _productService.GetAllProductsAsync(model.ProductIds);
            }


            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSale(SaleViewModel model, string imagePreviewDeteted, string productIdsStr)
        {
            ViewBag.Products = await _productService.GetProductsCanApplySaleAsync();

            if(productIdsStr is null)
            {
                model.ProductIds = await _saleDetailService.GetProductIdInSaleAsync(model.SaleId);

                ViewBag.ProductInSales = await _productService.GetAllProductsAsync(model.ProductIds);

                ViewBag.MessageError = "Lỗi không có sản phẩm nào được chọn";

                return View(model);
            }

            if (model.SaleType.Equals(TYPE_SALE_FOR_ORDER))
            {
                ModelState.Remove("ProductIds");
            }
            else
            {
                ModelState.Remove("FromOrderPrice");
            }
            var productIdsConvert = ConvertStringToListInt(productIdsStr);
            model.ProductIds = productIdsConvert;
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(imagePreviewDeteted))
                {
                    var imagesName = imagePreviewDeteted.Split(COMMA);
                    if (model.ImageFile != null && imagesName.Contains(model.ImageFile.FileName))
                    {
                        model.ImageFile = null;
                    }
                }

                using var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);
                try
                {
                    var sale = new Sale()
                    {
                        SaleId = model.SaleId,
                        SaleName = model.SaleName,
                        Description = model.Description,
                        SaleStartDate = model.SaleStartDate,
                        SaleEndDate = model.SaleEndDate,
                        Discount = model.Discount,
                        SaleType = model.SaleType,
                        Image = model.Image
                    };

                    string image = EMPTY;

                    if (model.ImageFile != null)
                    {
                        image = await SaveImageAsync(model.ImageFile, 384, 384, IMAGE_SALE_LINK);

                        if (image != EMPTY)
                        {
                            sale.Image = image;
                        }
                    }

                    var result = await _saleService.UpdateSaleAsync(sale);

                    if (model.SaleType.Equals(TYPE_SALE_FOR_PRODUCT))
                    {
                        var resultUpdate = await _saleDetailService.UpdateSaleDetailsAsync(model.ProductIds, model.Discount, model.SaleId, model.SaleStartDate, model.SaleEndDate);

                        if (resultUpdate > 0)
                        {
                            await _productService.UpdateSalePriceAsync();

                            transaction.Complete();

                            TempData["MessageSuccess"] = "Cập nhật khuyến mại thành công";

                            return Redirect("/Admin/Sale/Index");
                        }
                    }
                    else
                    {
                        transaction.Complete();

                        TempData["MessageSuccess"] = "Cập nhật khuyến mại thành công";

                        return View("/Admin/Sale/Index");
                    }
                }
                catch
                {
                    ViewBag.MessageError = "Lỗi hệ thống, vui lòng thử lại sau";
                }
            }

            //model.ProductIds = await _saleDetailService.GetProductIdInSaleAsync(model.SaleId);

            ViewBag.ProductInSales = await _productService.GetAllProductsAsync(model.ProductIds);

            return View(model);
        }

        public async Task<IActionResult> AddSale()
        {
            ViewBag.Products = await _productService.GetProductsCanApplySaleAsync();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddSale(SaleViewModel model, string imagePreviewDeteted, string productIdsStr)
        {
            ViewBag.Products = await _productService.GetProductsCanApplySaleAsync();

            if(productIdsStr is null)
            {
                ViewBag.MessageError = "Lỗi không có sản phẩm nào được chọn";

                return View(model);
            }

            if (model.SaleType.Equals(TYPE_SALE_FOR_ORDER))
            {
                ModelState.Remove("ProductIds");
            }
            else
            {
                ModelState.Remove("FromOrderPrice");
            }

            var productIdsConvert = ConvertStringToListInt(productIdsStr);

            model.ProductIds = productIdsConvert;

            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(imagePreviewDeteted))
                {
                    var imagesName = imagePreviewDeteted.Split(COMMA);
                    if (model.ImageFile != null && imagesName.Contains(model.ImageFile.FileName))
                    {
                        model.ImageFile = null;
                    }
                }

                using var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);
                try
                {
                    var sale = new Sale()
                    {
                        SaleName = model.SaleName,
                        Description = model.Description,
                        SaleStartDate = model.SaleStartDate,
                        SaleEndDate = model.SaleEndDate,
                        Discount = model.Discount,
                        SaleType = model.SaleType
                    };

                    var listNotifications = new List<Notification>();

                    var users = await _accountService.GetAllCustomersAsync();

                    if (model.SaleType.Equals(TYPE_SALE_FOR_ORDER))
                    {
                        sale.FromOrderPrice = model.FromOrderPrice;

FinalProject/Controllers/GuideController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Services.Interfacies;
using System;
using System.Threading.Tasks;

namespace FinalProject.Controllers
{
    public class GuideController : Controller
    {
        private readonly IFileGuideService _fileGuideService;
        private readonly IMemoryCache _memoryCache;

        public GuideController(IFileGuideService fileGuideService, IMemoryCache memoryCache)
        {
            _fileGuideService = fileGuideService;
            _memoryCache = memoryCache;
        }
        public IActionResult GuideBuyProduct()
        {
            return View();
        }
        public IActionResult GuidePayment()
        {
            return View();
        }

        public async Task<IActionResult> Download(string type)
        {
            bool cached = _memoryCache.TryGetValue(type, out FileGuide fileGuide);
            byte[] bytes;
            string contentType;
            if (!cached)
            {
                var result = await _fileGuideService.DownloadFileAsync(type);

                _memoryCache.Set(type, result);

                bytes = Convert.FromBase64String(result.Content);

                contentType = result.ContentType;
            }
            else
            {
                bytes = Convert.FromBase64String(fileGuide.Content);

                contentType = fileGuide.ContentType;
            }

            var file = new FileContentResult(bytes, contentType);

            return file;
        }
    }
}

FinalProject/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Interfacies;
using System.Collections.Generic;
using System.Threading.Tasks;
using X.PagedList;
using static Common.Constant;

namespace FinalProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICommentService _commentService;
        private readonly IRatingService _rateService;
        private readonly IUserConnectionService _userConnectionService;
        private readonly IRecommendationService _recommendationService;

        public ProductController(IProductService productService, ICommentService commentService, IRecommendationService recommendationService, IRatingService rateService, IUserConnectionService userConnectionService)
        {
            _productService = productService;
            _commentService = commentService;
            _recommendationService = recommendationService;
            _rateService = rateService;
            _userConnectionService = userConnectionService;
        }
        public async Task<IActionResult> Detail(int? id, int? page = 1)
        {
            if(id is null)
            {
                return PartialView(ERROR_404_PAGE);
            }

            var userConnection = Request.HttpContext.Connection.RemoteIpAddress;

            await _userConnectionService.AddUserConnectionAsync(userConnection.ToString(), id.Value);

            ViewBag.Product = await _productService.GetProductByIdAsync(id.Value);

            ViewBag.Comments = await _commentService.GetAllCommentsByProductIdAsync(id.Value);

            ViewBag.Ratings = await _rateService.GetRatingsAsync();

            ViewBag.RatingsDetail = await _rateService.GetRatingsDetailAsync(id.Value);

            var listProductDetailId = await _productService.GetProductDetailByProDuctIdAsync(id.Value);

            var productSuggests = await _recommendationService.GetSuggestedProduct(listProductDetailId);

            var model = productSuggests.ToPagedList(page.Value, 12);

            return View(model);
        }

        public string GetProductSkip(int? skip)
        {
            if(skip is null)
            {
                return ERROR_CODE_NULL.ToString();
            }

            try
            {
                return _productService.GetProductSkip(skip.Value);
            }
            catch
            {

            }

            return ERROR_CODE_SYSTEM.ToString();
        }
    }
}

FinalProject/Areas/Admin/Views/Shared/_Error404.cshtml
<!DOCTYPE html>
<html>

<head>
    <title>404 - Không tìm thấy trang</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/style/font-awesome/css/font-awesome.css">
    <link rel="stylesheet" href="~/style/css/error-page.css"/>
    <style>
        /* Login background */
        .background-body-login {
            background-image: url(../../images/background/bg.jpg);
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>
</head>

<body class="background-body-login">
    <section id="error">
        <div class="content">
            <i class="fa fa-warning"></i>
            <h1>404</h1>
            <p>Lỗi! - Không tìm thấy trang bạn yêu cầu</p>
            <div class="d-flex justify-content-center">
                <button class="btn btn-warning mg-5" type="button" onclick="goBack()">Quay lại</button>
                <a class="btn btn-success mg-5" asp-action="Dashboard" asp-controller="Home" asp-area="Admin">Quay lại trang chủ</a>
            </div>
        </div>
    </section>

    <script>
        function goBack() {
            window.history.back()
        }
    </script>
</body>

</html>

FinalProject/Areas/Admin/Views/Shared/_LeftNavigation.cshtml
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <li>
        <a class="sidebar-brand d-flex align-items-center justify-content-center"
           asp-action="Dashboard" asp-controller="Home" asp-area="Admin">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-address-book"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Stationery Admin</div>
        </a>
    </li>

    <li>
        <hr class="sidebar-divider my-0">
    </li>

    <li class="nav-item">
        <a class="nav-link" asp-action="Dashboard" asp-controller="Home" asp-area="Admin">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Bảng điều khiển</span>
        </a>
    </li>

    <li>
        <hr class="sidebar-divider">
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#banner" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-images"></i>
            <span>Quản lý quảng cáo</span>
        </a>
        <div id="banner" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" asp-action="Index" asp-controller="Banner" asp-area="Admin">Danh sách quảng cáo</a>
                <a class="collapse-item" asp-action="AddBanner" asp-controller="Banner" asp-area="Admin">Thêm quảng cáo</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-certificate"></i>
            <span>Quản lý loại sản phẩm</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Danh sách loại sản phẩm</a>
                <a class="collapse-item" asp-action="AddCategory" asp-controller="Category" asp-area="Admin">Thêm loại sản phẩm</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-atom"></i>
            <span>Quản lý sản phẩm</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" asp-action="Index" asp-controller="Product" asp-area="Admin">Danh sách sản phẩm</a>
                <a class="collapse-item" asp-action="AddProduct" asp-controller="Product" asp-area="Admin">Thêm sản phẩm</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#orderManagement" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-file-invoice"></i>
            <span>Quản lý đơn hàng</span>
        </a>
        <div id="orderManagement" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" asp-action="Index" asp-controller="Order" asp-area="Admin">Danh sách đơn hàng</a>
                <a class="collapse-item" asp-action="OrderWaitComfirm" asp-controller="Order" asp-area="Admin">Danh sách đơn hàng <br />chờ xác nhận</a>
                <a class="collapse-item" asp-action="OrderWaitExportWarehouse" asp-controller="Order" asp-area="Admin">Danh sách đơn hàng <br />chờ chuẩn bị</a>
                <a class="collapse-item" asp-action="OrderWaitToPick" asp-controller="Order" asp-area="Admin">Danh sách đơn hàng <br />chờ giao</a>
                <a class="collapse-item" asp-action="OrderDelivery" asp-controller="Order" asp-area="Admin">Danh sách đơn hàng <br />đang giao</a>
                <a class="collapse-item" asp-action="OrderDelivered" asp-controller="Order" asp-area="Admin">Danh sách đơn hàng <br />đã giao</a>
                <a class="collapse-item" asp-action="OrderReject" asp-controller="Order" asp-area="Admin">Danh sách đơn hàng <br />đã hủy</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#recommendationManagement" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-notes-medical"></i>
            <span>Quản lý khuyến nghị</span>
        </a>
        <div id="recommendationManagement" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" asp-action="ViewRecommendation" asp-controller="Warehouse" asp-area="Admin">Danh sách sản phẩm <br /> khuyến nghị</a>
            </div>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#importWarehouseManagement" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-notes-medical"></i>
            <span>Quản lý nhập kho</span>
        </a>
        <div id="importWarehouseManagement" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" asp-action="ListReceiptRequest" asp-controller="Warehouse" asp-area="Admin">Danh sách yêu cầu<br /> nhập kho</a>
                <a class="collapse-item" asp-action="ReceiptRequestWaitApprove" asp-controller="Warehouse" asp-area="Admin">Danh sách yêu cầu<br /> nhập kho chờ duyệt</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#saleManagement" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-piggy-bank"></i>
            <span>Quản lý khuyến mại</span>
        </a>
        <div id="saleManagement" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" asp-action="Index" asp-controller="Sale" asp-area="Admin">Danh sách khuyến mại</a>
                <a class="collapse-item" asp-action="AddSale" asp-controller="Sale" asp-area="Admin">Thêm khuyến mại</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#statisticalManagement" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-stream"></i>
            <span>Quản lý thống kê</span>
        </a>
        <div id="statisticalManagement" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" asp-action="Index" asp-controller="Statistical" asp-area="Admin">Thống kê doanh thu</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#guideManagement" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-book"></i>
            <span>Quản lý hướng dẫn</span>
        </a>
        <div id="guideManagement" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" asp-action="Index" asp-controller="Guide" asp-area="Admin">Danh sách các hướng dẫn</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#accountManagement" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-user"></i>
            <span>Quản lý tài khoản</span>
        </a>
        <div id="accountManagement" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" asp-action="Index" asp-controller="Account" asp-area="Admin">Danh sách tài khoản</a>
                <a class="collapse-item" asp-action="CreateEmployeeAccount" asp-controller="Account" asp-area="Admin">Thêm tài khoản</a>
            </div>
        </div>
    </li>

    <li>
        <hr class="sidebar-divider">
    </li>

    <li class="text-center">
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
    </li>
</ul>