FinalProject/Areas/Admin/ViewModels/BannerViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.ComponentModel.DataAnnotations;
using static Common.ValidationConstant;
using static Common.DisplayNameConstant;

namespace FinalProject.Areas.Admin.ViewModels
{
    public class BannerViewModel
    {
        public int BannerId { get; set; }

        [Required(ErrorMessage = ERROR_BANNER_IMAGE_EMPTY)]
        [Display(Name = DISPLAY_BANNER_IMAGE)]
        public IFormFile Image { get; set; }

        public string ImageString { get; set; }

        [Required(ErrorMessage = ERROR_BANNER_START_DATE_EMPTY)]
        [Display(Name = DISPLAY_BANNER_START_DATE)]
        public DateTime StartDate { get; set; } = DateTime.Now;

        [Required(ErrorMessage = ERROR_BANNER_END_DATE_EMPTY)]
        [Display(Name = DISPLAY_BANNER_END_DATE)]
        public DateTime EndDate { get; set; }

        [Display(Name = DISPLAY_BANNER_URL)]
        public string Url { get; set; } = "Default";
    }
}

FinalProject/Areas/Admin/Controllers/BannerController.cs
using Entities.Models;
using FinalProject.Areas.Admin.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Interfacies;
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;
using static Common.Constant;
using static Common.MessageConstant;
using static Common.RoleConstant;
using static Common.ValidationConstant;
using static FinalProject.Areas.Admin.Helpers.BannerHelper;
using static FinalProject.Areas.Admin.Helpers.ImageHelper;

namespace FinalProject.Areas.Admin.Controllers
{
    [Area(AREA_ADMIN)]
    [Authorize(Roles = ROLE_ADMIN, AuthenticationSchemes = ROLE_ADMIN)]
    public class BannerController : Controller
    {
        private readonly IBannerService _bannerService;

        public BannerController(IBannerService bannerService)
        {
            _bannerService = bannerService;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Banners = await _bannerService.GetAllBannerAsync();

            return View();
        }

        public IActionResult AddBanner()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddBanner(BannerViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var imageName = await SaveImageBannerAsync(model.Image, 1366, 768);

                    if (!(imageName is null))
                    {
                        using var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);

                        var banner = new Banner()
                        {
                            StartDate = model.StartDate,
                            EndDate = model.EndDate,
                            Image = imageName,
                            Url = model.Url
                        };

                        var result = await _bannerService.AddBannerAsync(banner);

                        if (result > 0)
                        {
                            transaction.Complete();

                            TempData["MessageSuccess"] = MESSAGE_SUCCESS_ADD_BANNER;

                            return Redirect("/Admin/Banner/Index");
                        }
                    }
                }
                catch
                {
                }
            }

            ViewBag.MessageError = MESSAGE_ERROR_SYSTEM;

            return View(model);
        }

        [HttpDelete]
        public async Task<int> DeleteBanner(int? bannerId)
        {
            if (bannerId is null)
            {
                return ERROR_CODE_NULL;
            }

            using var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);
            try
            {
                var result = await _bannerService.DeleteBannerAsync(bannerId.Value);

                if (result > 0)
                {
                    transaction.Complete();

                    return CODE_SUCCESS;
                }
            }
            catch { }

            return ERROR_CODE_SYSTEM;
        }

        public async Task<IActionResult> EditBanner(int? bannerId)
        {
            if (bannerId is null)
            {
                return PartialView(ERROR_404_PAGE_ADMIN);
            }

            var banner = await _bannerService.GetBannerByIdAsync(bannerId.Value);

            if (banner != null)
            {
                var model = ConvertBannerToBannerViewModel(banner);

                return View(model);
            }

            return PartialView(ERROR_404_PAGE_ADMIN);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditBanner(BannerViewModel model, string imagePreviewDeteted)
        {
            ModelState.Remove(KEY_IMAGE);

            var banner = await _bannerService.GetBannerByIdAsync(model.BannerId);

            if (ModelState.IsValid)
            {
                try
                {
                    string imageName = EMPTY;

                    if (imagePreviewDeteted != null)
                    {
                        var image = imagePreviewDeteted.Split(COMMA);

                        if (image.Contains(model.Image.FileName))
                        {
                            model.Image = null;
                        }
                    }

                    if (model.Image == null && model.ImageString == null)
                    {
                        ViewBag.MessageError = ERROR_BANNER_IMAGE_EMPTY;

                        model.ImageString = banner.Image;

                        return View(model);
                    }
                    else if (model.Image != null)
                    {

                        imageName = await SaveImageBannerAsync(model.Image, 1920, 768);
                    }
                    else if (model.ImageString != null)
                    {
                        imageName = model.ImageString;
                    }

                    banner.BannerId = model.BannerId;
                    banner.StartDate = model.StartDate;
                    banner.EndDate = model.EndDate;
                    banner.Image = imageName;
                    banner.Url = model.Url;

                    using var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);

                    var result = await _bannerService.UpdateBannerAsync(banner);

                    if (result > 0)
                    {
                        transaction.Complete();

                        TempData["MessageSuccess"] = MESSAGE_BANNER_UPDATE_SUCCESS;

                        model.ImageString = imageName;

                        return Redirect("/Admin/Banner/Index");
                    }
                }

                catch { }

            }

            model.ImageString = banner.Image;

            ViewBag.MessageError = MESSAGE_BANNER_UPDATE_FAIL;

            return View(model);
        }
    }
}

FinalProject/Areas/Admin/Views/Banner/AddBanner.cshtml
@model FinalProject.Areas.Admin.ViewModels.BannerViewModel
@{
    ViewData["Title"] = "Thêm quảng cáo";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">

    <h1 class="h3 mb-2 text-gray-800">Thêm quảng cáo</h1>
    <hr class="hr-end-list" />

    @if (!(ViewBag.MessageSuccess is null))
    {
        <div class="alert alert-success">@ViewBag.MessageSuccess</div>
    }
    @if (!(ViewBag.MessageError is null))
    {
        <div class="alert alert-danger">@ViewBag.MessageError</div>
    }

    <form asp-action="AddBanner" asp-controller="Banner" asp-area="Admin" method="post" role="form" enctype="multipart/form-data"
          id="form">

        @Html.AntiForgeryToken()
        <input type="hidden" name="imagePreviewDeteted" id="image-preview-deleted" />
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label asp-for="StartDate"></label>
                    <div class="input-wrapper">
                        <input type="text" id="start-date" asp-for="StartDate" class="form-field-input form-field-input-coupled" readonly />
                        <button id="start-date-button" type="button" class="btn btn-small">
                            <svg class="calendarIcon" aria-hidden="true" focusable="false" data-prefix="far"
                                 data-icon="calendar-alt" role="img" viewBox="0 0 448 512">
                                <path fill="currentColor"
                                      d="M148 288h-40c-6.6 0-12-5.4-12-12v-40c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12zm108-12v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 96v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm192 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96-260v352c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V112c0-26.5 21.5-48 48-48h48V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h128V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h48c26.5 0 48 21.5 48 48zm-48 346V160H48v298c0 3.3 2.7 6 6 6h340c3.3 0 6-2.7 6-6z" />
                            </svg>
                        </button>
                    </div>
                    <span class="text-danger" asp-validation-for="StartDate"></span>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label asp-for="EndDate"></label>
                    <div class="input-wrapper">
                        <input type="text" id="end-date" asp-for="EndDate" class="form-field-input form-field-input-coupled" readonly />
                        <button id="end-date-button" type="button" class="btn btn-small">
                            <svg class="calendarIcon" aria-hidden="true" focusable="false" data-prefix="far"
                                 data-icon="calendar-alt" role="img" viewBox="0 0 448 512">
                                <path fill="currentColor"
                                      d="M148 288h-40c-6.6 0-12-5.4-12-12v-40c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12zm108-12v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 96v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm192 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96-260v352c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V112c0-26.5 21.5-48 48-48h48V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h128V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h48c26.5 0 48 21.5 48 48zm-48 346V160H48v298c0 3.3 2.7 6 6 6h340c3.3 0 6-2.7 6-6z" />
                            </svg>
                        </button>
                    </div>
                    <span class="text-danger" asp-validation-for="EndDate"></span>
                </div>
            </div>
        </div>

        <div class="form-group form-flex" style="text-align: center;" id="show-image-preview">

        </div>

        <div class="form-group">
            <label asp-for="Image"></label>
            <input type="file" class="form-control-file" accept="image/*" asp-for="Image" onchange="previewImage(event)" id="images-file" />
            <span class="text-danger" asp-validation-for="Image"></span>
        </div>
    </form>

    <div class="form-group">
        <input type="button" value="Thêm quảng cáo" class="btn btn-success" onclick="submit()" />
    </div>
</div>
@section Scripts{
    <script type="text/javascript" src="~/js/calendar/mc-calendar.min.js"></script>
    <script type="text/javascript" src="~/js/calendar/calendar-helper.js"></script>
    <script type="text/javascript" src="~/admin/js/banner/add-banner.js"></script>
}

FinalProject/Areas/Admin/Views/Banner/EditBanner.cshtml
@model FinalProject.Areas.Admin.ViewModels.BannerViewModel
@{
    ViewData["Title"] = "Sửa quảng cáo";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">

    <h1 class="h3 mb-2 text-gray-800">Sửa quảng cáo</h1>
    <hr class="hr-end-list" />

    @if (!(ViewBag.MessageSuccess is null))
    {
        <div class="alert alert-success">@ViewBag.MessageSuccess</div>
    }
    @if (!(ViewBag.MessageError is null))
    {
        <div class="alert alert-danger">@ViewBag.MessageError</div>
    }

    <form asp-action="EditBanner" asp-controller="Banner" asp-area="Admin" method="post" role="form" enctype="multipart/form-data"
          id="form">

        @Html.AntiForgeryToken()
        <input type="hidden" name="imagePreviewDeteted" id="image-preview-deleted" />
        <input type="hidden" name="ImageString" value="@Model.ImageString" id="image-deleted" />
        <input type="hidden" asp-for="BannerId" />
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label asp-for="StartDate"></label>
                    <div class="input-wrapper">
                        <input type="text" id="start-date" asp-for="StartDate" value="@Model.StartDate.ToString("MM-dd-yyyy")" class="form-field-input form-field-input-coupled" readonly />
                        <button id="start-date-button" type="button" class="btn btn-small">
                            <svg class="calendarIcon" aria-hidden="true" focusable="false" data-prefix="far"
                                 data-icon="calendar-alt" role="img" viewBox="0 0 448 512">
                                <path fill="currentColor"
                                      d="M148 288h-40c-6.6 0-12-5.4-12-12v-40c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12zm108-12v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 96v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm192 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96-260v352c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V112c0-26.5 21.5-48 48-48h48V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h128V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h48c26.5 0 48 21.5 48 48zm-48 346V160H48v298c0 3.3 2.7 6 6 6h340c3.3 0 6-2.7 6-6z" />
                            </svg>
                        </button>
                    </div>
                    <span class="text-danger" asp-validation-for="StartDate"></span>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label asp-for="EndDate"></label>
                    <div class="input-wrapper">
                        <input type="text" id="end-date" asp-for="EndDate" value="@Model.EndDate.ToString("MM-dd-yyyy")" class="form-field-input form-field-input-coupled" readonly />
                        <button id="end-date-button" type="button" class="btn btn-small">
                            <svg class="calendarIcon" aria-hidden="true" focusable="false" data-prefix="far"
                                 data-icon="calendar-alt" role="img" viewBox="0 0 448 512">
                                <path fill="currentColor"
                                      d="M148 288h-40c-6.6 0-12-5.4-12-12v-40c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12zm108-12v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 96v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm192 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96-260v352c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V112c0-26.5 21.5-48 48-48h48V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h128V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h48c26.5 0 48 21.5 48 48zm-48 346V160H48v298c0 3.3 2.7 6 6 6h340c3.3 0 6-2.7 6-6z" />
                            </svg>
                        </button>
                    </div>
                    <span class="text-danger" asp-validation-for="EndDate"></span>
                </div>
            </div>
        </div>

        <div class="form-group form-flex" style="text-align: center;" id="show-image-preview">
            @if (Model.ImageString != null)
            {
                <div class="show-image">
                    <img src="~/images/banner/@Model.ImageString" class="image-product" style="width: 100%; height: 60%;" />
                    <i class="delete fa fa-times" onclick="confirmDeleteImage(this)">
                    </i>
                </div>
            }
        </div>

        <div class="form-group">
            <label asp-for="Image"></label>
            <input type="file" class="form-control-file" accept="image/*" asp-for="Image" onchange="previewImage(event)" id="images-file" />
            <span class="text-danger" asp-validation-for="Image"></span>
        </div>
    </form>

    <div class="form-group">
        <input type="button" value="Sửa quảng cáo" class="btn btn-success" onclick="submit()" />
    </div>
</div>
@section Scripts{
    <script type="text/javascript" src="~/js/calendar/mc-calendar.min.js"></script>
    <script type="text/javascript" src="~/js/calendar/calendar-helper.js"></script>
    <script type="text/javascript" src="~/admin/js/banner/update-banner.js"></script>
}

FinalProject/Areas/Admin/Views/Banner/Index.cshtml
@{
    ViewData["Title"] = "Quản lý quảng cáo";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var banners = ViewBag.Banners as IList<Entities.Models.Banner>;
}

<div class="container-fluid">

    <h1 class="h3 mb-2 text-gray-800">Thông tin quảng cáo</h1>
    @if(TempData["MessageSuccess"] != null) 
    {
        <div class="alert alert-success">@TempData["MessageSuccess"]</div>
    }
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">
                <a class="btn btn-primary" asp-action="AddBanner" asp-controller="Banner" asp-area="Admin">
                    Thêm quảng cáo
                </a>
            </h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Hình ảnh</th>
                            <th>Ngày bắt đầu</th>
                            <th>Ngày kết thúc</th>
                            <th>Hành động</th>
                        </tr>
                    </thead>
                    <tbody>

                        @if (!(banners is null))
                        {
                            foreach (var item in banners)
                            {
                                <tr>
                                    <td>@item.BannerId</td>
                                    <td><img src="~/images/banner/@item.Image" width="100" height="100" alt="Alternate Text" /></td>
                                    <td>@item.StartDate.ToShortDateString()</td>
                                    <td>@item.EndDate.ToShortDateString()</td>
                                    <td>
                                        <a onclick="deleteBanner(this, @item.BannerId)" style="cursor: pointer; color: #4e73df">Xóa</a>
                                        <a asp-action="EditBanner" asp-controller="Banner"
                                           asp-area="Admin" asp-route-bannerId="@item.BannerId" style="cursor: pointer; color: #4e73df">Sửa</a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section Scripts{ 
    <script src="~/js/notify/notify-helper.js"></script>
    <script src="~/admin/js/banner/banner-index.js"></script>
}